[package]
name = "flywheel"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.11.0"
#wide = "0.7.33" # simd stuff

[dev-dependencies]
rand = "0.8"
criterion = { version = "0.7", features = ["html_reports"] }

[[bin]]
name = "project"
path = "src/main.rs"

[[bench]]
#path = "src/bench/matrix.rs"
name = "matrix"
harness = false

[profile.dev.package."*"]
opt-level = 3